USE arcadia_test;

CREATE TABLE Users (
	Id int PRIMARY KEY IDENTITY,
	Email VARCHAR(30) NOT NULL UNIQUE,
	Hash VARCHAR(64) NOT NULL,
	Name VARCHAR(30) NOT NULL
);

CREATE TABLE TaskStatus (
	Name VARCHAR(10) NOT NULL PRIMARY KEY
);

INSERT INTO TaskStatus (name) VALUES ('Active'), ('Cancelled'), ('Resolved');

CREATE TABLE Tasks (
	Id int PRIMARY KEY IDENTITY,
	UserId int NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
	Name VARCHAR(50) NOT NULL,
	Description TEXT,
	Type VARCHAR(10),
	DueDate DATE,
	Status VARCHAR(10) REFERENCES TaskStatus(Name) 
);

CREATE TABLE TaskChanges (
	Id int PRIMARY KEY IDENTITY,
	TaskId int REFERENCES Tasks(id) ON DELETE CASCADE,
	Operation VARCHAR(15) NOT NULL,
	ChangedAt DATETIME NOT NULL,
	OldValue TEXT,
	NewValue TEXT
);
