//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcadiaTest.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskChange
    {
        public int Id { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string Operation { get; set; }
        public System.DateTime ChangedAt { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
